FROM ubuntu:22.04
RUN apt-get update && apt-get install -y git python3 python3-pip python-is-python3 && apt-get clean all

WORKDIR /apps/comfyui
RUN git clone https://github.com/comfyanonymous/ComfyUI.git -b v0.2.2 /apps/comfyui
RUN pip install -r requirements.txt --no-cache-dir
CMD python main.py --listen --multi-user
