services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_USER: JOHNAIC
      CLICKHOUSE_PASSWORD: PleaseChangeMe@123
      CLICKHOUSE_DB: clickhouse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    deploy:
      resources:
        limits:
          memory: 200G
    ports:
      - "8123:8123"   
      - "9000:9000"   
    volumes:
      - /data/benchmarking/clickhouse_data:/var/lib/clickhouse
      - /data/benchmarking/clikchouse_logs:/var/log/clickhouse-server/
