(brilisp
    (define ((print int) (n int)))

    (define ((main int))
        (set (one int) (const 1))
        (set (i int) (const 2))
        (set (i_m_1 int) (const 1))
        (set (i_m_2 int) (const 0))
        (set (n int) (const 10))
        (set (seq (ptr int)) (alloc n))

        (set (v int) (const 0))
        (store seq v)
        (set (v int) (const 1))
        (set (p (ptr int)) (ptradd seq i_m_1))
        (store p v)

        (label calc_i)
        (set (p_m_2 (ptr int)) (ptradd seq i_m_2))
        (set (p_m_1 (ptr int)) (ptradd seq i_m_1))
        (set (v_m_2 int) (load p_m_2))
        (set (v_m_1 int) (load p_m_1))
        (set (v int) (add v_m_1 v_m_2))
        (set (p (ptr int)) (ptradd seq i))
        (store p v)
        (set (i_m_1 int) (add i_m_1 one))
        (set (i_m_2 int) (add i_m_2 one))
        (set (i int) (add i one))
        (set (loop bool) (le i n))
        (br loop calc_i out)

        (label out)
        (set (i int) (sub n one))
        (set (p (ptr int)) (ptradd seq i))
        (set (v int) (load p))
        (set (tmp int) (call print v))
        (ret tmp)))
