(brilisp
    (define ((print int) (n int)))

    (define ((elem int) (i int) (j int))
        (set (two int) (const 2))
        (set (j int) (mul j two))
        (set (i int) (add i j))
        (ret i))

    ;; Flat array helpers: index = i * 3 + j
    (define ((arr_read int) (arr (ptr int)) (i int) (j int))
        (set (tmp int) (mul i 3))
        (set (idx int) (add tmp j))
        (set (p (ptr int)) (ptradd arr idx))
        (set (v int) (load p))
        (ret v))

    (define ((arr_write void) (arr (ptr int)) (i int) (j int) (v int))
        (set (tmp int) (mul i 3))
        (set (idx int) (add tmp j))
        (set (p (ptr int)) (ptradd arr idx))
        (store p v)
        (ret))

    (define ((main void))
        (set (one int) (const 1))
        (set (three int) (const 3))
        ;; Allocate the 3x3 matrix as a flat array of 9 ints.
        (set (arr (ptr int)) (alloc 9))
        (set (i int) (const 0))
        (set (j int) (const 0))

        (label init_row)
        (label init_col)
        (set (v int) (call elem i j))
        (set (tmp void) (call arr_write arr i j v))
        (set (j int) (add j one))
        (set (j_loop bool) (lt j three))
        (br j_loop init_col cont1)
        (label cont1)
        (set (j int) (const 0))
        (set (i int) (add i one))
        (set (i_loop bool) (lt i three))
        (br i_loop init_row cont2)

        (label cont2)
        (set (i int) (const 0))
        (set (j int) (const 0))

        (label calc_row)
        (set (j int) (add i one))
        (label calc_col)
        (set (vij int) (call arr_read arr i j))
        (set (vji int) (call arr_read arr j i))
        (set (tmp void) (call arr_write arr i j vji))
        (set (tmp void) (call arr_write arr j i vij))
        (set (j int) (add j one))
        (set (j_loop bool) (lt j three))
        (br j_loop calc_col cont3)
        (label cont3)
        (set (j int) (const 0))
        (set (i int) (add i one))
        (set (i_loop bool) (lt i three))
        (br i_loop calc_row cont4)

        (label cont4)
        (set (i int) (const 0))
        (set (j int) (const 0))

        (label out_row)
        (label out_col)
        (set (v int) (call arr_read arr i j))
        (set (tmp int) (call print v))
        (set (j int) (add j one))
        (set (j_loop bool) (lt j three))
        (br j_loop out_col cont5)
        (label cont5)
        (set (j int) (const 0))
        (set (i int) (add i one))
        (set (i_loop bool) (lt i three))
        (br i_loop out_row cont6)

        (label cont6)
        (ret)))
