FROM ubuntu:24.04

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv curl gnupg unzip libaio1t64

# REQUIRED for Oracle on Ubuntu 24.04 (t64 transition)
RUN ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 \
          /usr/lib/x86_64-linux-gnu/libaio.so.1

RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

WORKDIR /app/etl

# Oracle Instant Client (THICK MODE)
RUN mkdir -p /opt/oracle && \
    cd /opt/oracle && \
    curl -L -o instantclient-basic.zip \
      -H "Cookie: oraclelicense=accept-securebackup-cookie" \
      https://download.oracle.com/otn_software/linux/instantclient/2120000/instantclient-basic-linux.x64-21.20.0.0.0dbru.zip && \
    unzip instantclient-basic.zip && \
    rm instantclient-basic.zip && \
    echo /opt/oracle/instantclient_21_20 > /etc/ld.so.conf.d/oracle-instantclient.conf && \
    ldconfig

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_21_20


# install mssql odbc driver
RUN curl -sSL -O https://packages.microsoft.com/config/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2)/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 && ACCEPT_EULA=Y apt-get install -y mssql-tools18
ENV PATH="/opt/mssql-tools18/bin:$PATH"
RUN apt-get install -y unixodbc-dev


ADD requirements.txt .
RUN /venv/bin/pip install -r requirements.txt

ADD . .
RUN /venv/bin/pip install .

CMD ["bash"]
