# Generated by Django 5.2.9 on 2025-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconfiguration",
            name="database_type",
            field=models.CharField(
                choices=[
                    ("postgres", "Postgres"),
                    ("clickhouse", "Clickhouse"),
                    ("mssql", "Mssql"),
                    ("oracle", "Oracle"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="databaseconfiguration",
            name="etl_type",
            field=models.CharField(
                choices=[("source", "Source"), ("target", "Target")]
            ),
        ),
    ]
