# Generated by Django 5.2.9 on 2025-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0004_etlconfiguration_run_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etlconfiguration",
            name="run_interval",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
