# Generated by Django 5.2.9 on 2026-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0005_alter_etlconfiguration_run_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="etlconfiguration",
            name="replication_mode",
            field=models.CharField(
                choices=[
                    ("incremental", "Incremental"),
                    ("full_refresh", "Full Refresh"),
                    ("one_time", "One Time"),
                ],
                default="incremental",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="etlconfiguration",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("paused", "Paused")],
                default="active",
                max_length=10,
            ),
        ),
    ]
