(c-lisp
  (define ((llvm.nvvm.read.ptx.sreg.tid.x int)))
  (define ((llvm.nvvm.read.ptx.sreg.ntid.x int)))
  (define ((llvm.nvvm.read.ptx.sreg.ctaid.x int)))
  (define ((kernel void)
           (a (ptr float))
           (b (ptr float))
           (c (ptr float))
           (n int))
    (declare x int)
    (set x
         (add (call llvm.nvvm.read.ptx.sreg.tid.x)
              (mul (call llvm.nvvm.read.ptx.sreg.ntid.x)
                   (call llvm.nvvm.read.ptx.sreg.ctaid.x))))
    (if (lt x n)
      (store (ptradd c x)
             (fadd (load (ptradd a x)) (load (ptradd b x)))))))