(define-app
    (version "3.28")
    (ports 3000)
    (let ((db-password ,(gen-password))
          (clickhouse-password ,(gen-password))
          (minio-password ,(gen-password))
          (redis-password ,(gen-password))
          (salt ,(gen-password))
          (encryption-key ,(gen-password-hex32)))
        (containers
            (container
                (name "worker")
                (image "docker.io/langfuse/langfuse-worker:3.28")
                (environment
                    ("DATABASE_URL" ,(format "postgres://postgres:{}@localhost:5432/postgres" ,db-password))
                    ("SALT" ,salt)
                    ("ENCRYPTION_KEY" ,encryption-key)
                    ("TELEMETRY_ENABLED" "false")
                    ("LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES" "true")
                    ("CLICKHOUSE_MIGRATION_URL" "clickhouse://localhost:9000")
                    ("CLICKHOUSE_URL" "http://localhost:8123")
                    ("CLICKHOUSE_USER" "clickhouse")
                    ("CLICKHOUSE_PASSWORD" ,clickhouse-password)
                    ("CLICKHOUSE_CLUSTER_ENABLED" "false")
                    ("LANGFUSE_S3_EVENT_UPLOAD_BUCKET" "langfuse")
                    ("LANGFUSE_S3_EVENT_UPLOAD_REGION" "auto")
                    ("LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID" "minio")
                    ("LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY" ,minio-password)
                    ("LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT" "http://localhost:9001")
                    ("LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE" "true")
                    ("LANGFUSE_S3_EVENT_UPLOAD_PREFIX" "events/")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_BUCKET" "langfuse")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_REGION" "auto")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID" "minio")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY" ,minio-password)
                    ("LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT" "http://localhost:9001")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE" "true")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_PREFIX" "media/")
                    ("REDIS_HOST" "localhost")
                    ("REDIS_PORT" "6379")))
            (container
                (name "web")
                (image "docker.io/langfuse/langfuse:3.28")
                (environment
                    ("DATABASE_URL" ,(format "postgres://postgres:{}@localhost:5432/postgres" ,db-password))
                    ("SALT" ,salt)
                    ("ENCRYPTION_KEY" ,encryption-key)
                    ("TELEMETRY_ENABLED" "false")
                    ("LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES" "true")
                    ("CLICKHOUSE_MIGRATION_URL" "clickhouse://localhost:9000")
                    ("CLICKHOUSE_URL" "http://localhost:8123")
                    ("CLICKHOUSE_USER" "clickhouse")
                    ("CLICKHOUSE_PASSWORD" ,clickhouse-password)
                    ("CLICKHOUSE_CLUSTER_ENABLED" "false")
                    ("LANGFUSE_S3_EVENT_UPLOAD_BUCKET" "langfuse")
                    ("LANGFUSE_S3_EVENT_UPLOAD_REGION" "auto")
                    ("LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID" "minio")
                    ("LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY" ,minio-password)
                    ("LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT" "http://localhost:9001")
                    ("LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE" "true")
                    ("LANGFUSE_S3_EVENT_UPLOAD_PREFIX" "events/")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_BUCKET" "langfuse")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_REGION" "auto")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID" "minio")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY" ,minio-password)
                    ("LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT" "http://localhost:9001")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE" "true")
                    ("LANGFUSE_S3_MEDIA_UPLOAD_PREFIX" "media/")
                    ("REDIS_HOST" "localhost")
                    ("REDIS_PORT" "6379")
                    ; common as above
                    ("NEXTAUTH_URL" ,(interactive-input "Langfuse URL" "Enter the domain address where you want langfuse hosted. Example: https://langfuse.johnaic.com"))
                    ("NEXTAUTH_SECRET" ,(gen-password))))
            (container
                (name "clickhouse")
                (image "docker.io/clickhouse/clickhouse-server:latest")
                (environment
                    ("CLICKHOUSE_DB" "default")
                    ("CLICKHOUSE_USER" "clickhouse")
                    ("CLICKHOUSE_PASSWORD" ,clickhouse-password))
                (volumes
                    ("clickhouse_data" "/var/lib/clickhouse")
                    ("clickhouse_logs" "/var/log/clickhouse-server")))
            (container
                (name "minio")
                (image "docker.io/minio/minio:latest")
                (entrypoint "sh")
                (command "-c 'mkdir -p /data/langfuse && minio server --address \":9001\" --console-address \":9002\" /data'")
                (environment
                    ("MINIO_ROOT_USER" "minio")
                    ("MINIO_ROOT_PASSWORD" ,minio-password))
                (volumes
                    ("minio_data" "/data")))
            (container
                (name "redis")
                (image "docker.io/library/redis:7.4"))
            (container
                (name "db")
                (image "docker.io/library/postgres:16.2")
                (volumes
                    ("data" "/var/lib/postgresql/data/"))
                (environment
                    ("POSTGRES_DB" "postgres")
                    ("POSTGRES_USER" "postgres")
                    ("POSTGRES_PASSWORD" ,db-password))))))
