FROM ubuntu:22.04

WORKDIR /apps/automatic111
RUN apt-get update && apt-get install -y wget git python3 python3-venv libgl1 libglib2.0-0 google-perftools bc && apt-get clean all
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git -b v1.10.0 /apps/automatic111
CMD bash webui.sh -f --listen
