# Generated by Django 5.2.9 on 2025-12-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etl_type",
                    models.CharField(
                        choices=[("source", "source"), ("target", "target")]
                    ),
                ),
                (
                    "database_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "postgresql"),
                            ("clickhouse", "clickhouse"),
                            ("mssql", "mssql"),
                            ("oracle", "oracle"),
                        ]
                    ),
                ),
                ("connection_config", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ETLConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_table", models.CharField()),
                ("target_table", models.CharField()),
                ("replication_key", models.CharField(null=True)),
                ("replication_state", models.JSONField(null=True)),
                (
                    "source_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="databank.databaseconfiguration",
                    ),
                ),
                (
                    "target_database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="databank.databaseconfiguration",
                    ),
                ),
            ],
        ),
    ]
