# Generated by Django 5.2.9 on 2025-12-09 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0002_alter_databaseconfiguration_database_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconfiguration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="databaseconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="etlconfiguration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="etlconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
