# Generated by Django 5.2.9 on 2025-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databank", "0003_databaseconfiguration_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etlconfiguration",
            name="run_interval",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="etlconfiguration",
            name="replication_key",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="etlconfiguration",
            name="replication_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
