(c-lisp
     (define ((llvm.nvvm.read.ptx.sreg.tid.x int)))
     (define ((llvm.nvvm.read.ptx.sreg.ctaid.x int)))
     (define ((llvm.nvvm.barrier0 void)))
     (define-global (shared_data (arr 8 float)) (addrspace 3))
     (define ((llvm.nvvm.shfl.sync.down.f32 float) 
               (mask int) 
               (val float) 
               (delta int) 
               (clamp int)))

     
     (define ((kernel void)
               (output_data (ptr float))
               (input_data (ptr float))
               (num_ele_per_batch int))

          (if (eq (rem 256 32) 0)
               ((declare block_idx int)
               (set block_idx (call llvm.nvvm.read.ptx.sreg.ctaid.x))
               (declare block_sum float)
               (set input_data (ptradd input_data (mul block_idx num_ele_per_batch)))
               (declare num_elem_per_thread int)
               (set num_elem_per_thread (div 
                                            (sub (add num_ele_per_batch 256) 1) 
                                            256))
               (declare thread_idx int)
               (set thread_idx (call llvm.nvvm.read.ptx.sreg.tid.x))
               (declare sum float)
               (set sum 0.0)
               (declare offset int)
               (declare i int)
               (for ((set i 0) (lt i num_elem_per_thread) (set i (add i 1)))
                    (set offset (add thread_idx (mul i 256)))
                    (if (lt offset num_ele_per_batch)
                         (set sum (fadd sum (load (ptradd input_data offset))))))
               (declare FULL_MASK int)
             ;;  (set FULL_MASK #{0xffffffff}#)
              ;; (set FULL_MASK 4294967295)
               (set FULL_MASK -1)
               (for ((set offset 16) (gt offset 0) (set offset (div offset 2)))
                     (set sum (fadd sum (call llvm.nvvm.shfl.sync.down.f32 FULL_MASK sum offset 32))))
               (if (eq (rem (call llvm.nvvm.read.ptx.sreg.tid.x) 32) 0)
                    (store (aptradd shared_data (div (call llvm.nvvm.read.ptx.sreg.tid.x) 32)) sum))
               (call llvm.nvvm.barrier0)
               (set sum 0.0)
               (for ((set i 0) (lt i 8) (set i (add i 1)))
                    (set sum (fadd sum (load (aptradd shared_data i)))))
               (set block_sum sum)
               (if (eq thread_idx 0)
                   (store (ptradd output_data block_idx) block_sum))))
          (ret)))
