# Generated by Django 5.2.9 on 2025-12-09 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_graph_task_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="next_run_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="periodic_interval",
            field=models.FloatField(null=True),
        ),
    ]
