# Generated by Django 6.0 on 2025-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField()),
                ("image", models.CharField()),
                ("name", models.CharField()),
                ("command", models.CharField()),
                ("created", models.CharField()),
                ("status", models.CharField()),
            ],
        ),
    ]
