# Generated by Django 5.2.9 on 2025-12-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_task_next_run_at_task_periodic_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_manager.graph",
            ),
        ),
    ]
